"use server";

import nodemailer from "nodemailer";

export async function submitLeadAction(formData: FormData) {
  try {
    const name = formData.get("name") as string;
    const email = formData.get("email") as string;
    const phone = formData.get("phone") as string;
    const country = formData.get("country") as string;
    const course = formData.get("course") as string;
    const message = formData.get("message") as string;

    // Validate required fields
    if (!name || !email || !phone || !course) {
      return { success: false, error: "Please fill out all required fields." };
    }

    const gmailUser = process.env.GMAIL_USER;
    const gmailPass = process.env.GMAIL_APP_PASSWORD;

    if (!gmailUser || !gmailPass) {
      console.error("Gmail credentials are not configured in environment variables.");
      return { success: false, error: "Server configuration error. Please try again later." };
    }

    // Configure Nodemailer transporter for Gmail
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: gmailUser,
        pass: gmailPass,
      },
    });

    // Format the email content
    const mailOptions = {
      from: `"Recite Ayah System" <${gmailUser}>`, // Sender address
      to: gmailUser, // Send to the admin's own email
      subject: `🎉 New Free Trial Request from ${name}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
          <div style="background-color: #1B3625; padding: 20px; text-align: center;">
            <h2 style="color: #ffffff; margin: 0;">New Lead Received!</h2>
          </div>
          <div style="padding: 30px; background-color: #ffffff;">
            <p style="font-size: 16px; color: #374151;">A new student has requested a free trial. Here are their details:</p>
            
            <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #1f2937; width: 30%;">Name</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; color: #4b5563;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #1f2937;">Email</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; color: #4b5563;"><a href="mailto:${email}">${email}</a></td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #1f2937;">Phone / WhatsApp</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; color: #4b5563;">${phone}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #1f2937;">Country</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; color: #4b5563;">${country || "Not provided"}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #1f2937;">Course Interest</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; color: #4b5563;">${course}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #1f2937;">Notes</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; color: #4b5563; white-space: pre-wrap;">${message || "No additional notes."}</td>
              </tr>
            </table>
            
            <div style="margin-top: 30px; text-align: center;">
              <a href="https://wa.me/${phone.replace(/[^0-9]/g, '')}" style="display: inline-block; background-color: #25D366; color: #ffffff; text-decoration: none; padding: 12px 24px; border-radius: 4px; font-weight: bold;">Message on WhatsApp</a>
            </div>
          </div>
          <div style="background-color: #f9fafb; padding: 15px; text-align: center; font-size: 12px; color: #6b7280;">
            This email was automatically generated by your Recite Ayah website.
          </div>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);

    return { success: true };
  } catch (error) {
    console.error("Error sending email:", error);
    return { success: false, error: "Failed to send email. Please try again." };
  }
}
